Create project skeleton v2
kommitters/okdose-dapp pull request #19
Opened 2022-12-19 13:44 UTC by LauraVilladakommit

## Description

I changed the folder structure for the back-end section "okdose" according to the changes we made in the SAD. 

Fixes #3

2022-12-23 14:53 UTC, jcamilocp requested changes
Let's add the Contracts folder extraction to this ticket's scope. I'm not sure if the creation of all folders inside the Transmission Types was needed for this first structure

2022-12-23 14:53 UTC, jcamilocp commented on .nvmrc
> +16
Is this file needed?

2022-12-23 14:53 UTC, jcamilocp commented on okdose/build.sh
> +#!/bin/sh
Do we need to move this file to the Contracts folder?

2022-12-23 14:53 UTC, jcamilocp commented on okdose/deploy.sh
> +#!/bin/sh
Same here. I think we should move them to the Contracts' folder

2022-12-23 15:01 UTC, LauraVilladakommit commented on .nvmrc
> +16
This file was created to specify the Node version we need to use, so using nvm the dependencies will be according to that version

2022-12-23 15:03 UTC, LauraVilladakommit commented on okdose/build.sh
> +#!/bin/sh
The contracts folder structure could not be defined in this initial setup because it depended on the NEAR wallet setup, so this changes were done in that ticket

2022-12-23 15:22 UTC, jcamilocp commented on okdose/build.sh
> +#!/bin/sh
Let's remove those files

2022-12-26 15:41 UTC, jcamilocp approved these changes
LGTM

2022-12-26 16:19 UTC, merged