Create smart contract for Pentamidine isethionate
kommitters/okdose-dapp pull request #32
Opened 2023-01-11 16:07 UTC by keliumJU

## Description

The translation keys were added for the Pentamidine Isethionate contract.

Fixes #18

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-01-12 14:44 UTC, einerzg submitted a review, later dismissed
Some comments @keliumJU.

2023-01-12 14:44 UTC, einerzg commented on okdose/package.json
> +    "yarn": "^1.22.19"
Please remove this line. Install `yarn` global for you!!!

2023-01-12 14:44 UTC, einerzg commented on okdose/transmissionTypes/transmittedByVectors/leishmaniasis/index.js
> +  nearInterface.viewMethod(process.env.PENTAMIDINE_CONTRACT, 'get_dose', { weight })
`get_dose` should be a const.

2023-01-12 14:44 UTC, einerzg commented on okdose/transmissionTypes/transmittedByVectors/leishmaniasis/index.js
> +export { prescribeNMetilGlucamine, prescribeSodiumStibogluconate, prescribePentamidineIsethionate };
change the format to:

```
export { 
    prescribeNMetilGlucamine,
    prescribeSodiumStibogluconate,
    prescribePentamidineIsethionate
};
```

2023-01-12 14:44 UTC, einerzg commented on okdoseweb/App.js
> +import { prescribePentamidineIsethionate } from '../okdose/transmissionTypes/transmittedByVectors/leishmaniasis';
this path is too long, you can use this to solve the case:

https://www.npmjs.com/package/babel-plugin-module-resolver

2023-01-12 14:44 UTC, einerzg commented on okdoseweb/App.js
> +    prescribePentamidineIsethionate(nearInterface, 80)
Please, avoid hardcoding code. For this case create a const for 80.

2023-01-12 14:44 UTC, einerzg commented on okdoseweb/App.js
> +import { prescribePentamidineIsethionate } from '../okdose/transmissionTypes/transmittedByVectors/leishmaniasis';
@LauraVilladakommit

2023-01-12 16:30 UTC, jcamilocp commented on okdose/transmissionTypes/transmittedByVectors/leishmaniasis/index.js
> +  nearInterface.viewMethod(process.env.PENTAMIDINE_CONTRACT, 'get_dose', { weight })
We thought of doing that. Maybe we can declare it as a const, as it's the same for almost every contract

2023-01-12 16:31 UTC, jcamilocp commented on okdoseweb/App.js
> +import { prescribePentamidineIsethionate } from '../okdose/transmissionTypes/transmittedByVectors/leishmaniasis';
This file is just being used for tests. It won't be like that for the final version.

2023-01-12 16:33 UTC, jcamilocp commented on okdoseweb/App.js
> +    prescribePentamidineIsethionate(nearInterface, 80)
Just testing again. 80 isn't a meaningful value, just a random one

2023-01-12 16:35 UTC, LauraVilladakommit commented on okdoseweb/App.js
> +    prescribePentamidineIsethionate(nearInterface, 80)
@einerzg That file is just to test the call to the contract from the UI, the components will have a weight prop to pass to the prescription.

2023-01-13 14:31 UTC, keliumJU commented on okdose/package.json
> +    "yarn": "^1.22.19"
I think it was installed by version manager **asdf**, I remove it now

2023-01-13 14:33 UTC, keliumJU commented on okdose/transmissionTypes/transmittedByVectors/leishmaniasis/index.js
> +export { prescribeNMetilGlucamine, prescribeSodiumStibogluconate, prescribePentamidineIsethionate };
it looks better :)

2023-01-13 14:37 UTC, keliumJU commented on okdoseweb/App.js
> +    prescribePentamidineIsethionate(nearInterface, 80)
I created a weight constant for the test

2023-01-16 16:32 UTC, jcamilocp reviewed
Question: should we update the README, adding the steps to create the `contracts.env` file? @LauraVilladakommit

2023-01-16 16:32 UTC, jcamilocp commented on .gitignore
> +/okdose/contracts.env
I think we should move the `.env` file to the root folder, as it is mainly used in the front-end

2023-01-16 16:32 UTC, jcamilocp commented on okdoseweb/package.json
> +    "start": "env-cmd -f ../okdose/contracts.env parcel index.html --open",
If we decide to move the file, we should change this line

2023-01-16 16:33 UTC, jcamilocp commented on okdoseweb/App.js
> +    prescribePentamidineIsethionate(nearInterface, 80)
That's enough for me tbh. @einerzg what do you think?

2023-01-16 19:01 UTC, einerzg commented on okdoseweb/package-lock.json
> +{
What will you use `npm` or `yarn`? @keliumJU & @LauraVilladakommit

2023-01-16 19:02 UTC, einerzg commented on package-lock.json
> +{
What will you use npm or yarn?

2023-01-16 19:10 UTC, keliumJU commented on package-lock.json
> +{
here too, we will only use yarn :)

2023-01-17 19:40 UTC, keliumJU commented
@einerzg the error that presented the linter in the CI was solved, @jcamilocp  new features were added to the linter to control the imports by means of aliases with the module resolver of babel, probably the same process should be done in okdose and okdose-dapp-contract.

2023-01-17 21:56 UTC, jcamilocp requested changes

2023-01-17 21:56 UTC, jcamilocp commented on okdoseweb/package.json
> +    "add": "^2.0.6",
Remove this, please

2023-01-17 21:56 UTC, jcamilocp commented on okdoseweb/package.json
> +    "yarn": "^1.22.19"
And remove this also

2023-01-17 21:56 UTC, jcamilocp commented on okdoseweb/package.json
>      "eslint-config-airbnb": "^19.0.4",
Should we remove this dependency?

2023-01-17 21:56 UTC, jcamilocp commented on okdoseweb/index.js
>  // React
Let's remove this line

2023-01-17 22:39 UTC, keliumJU commented on okdoseweb/package.json
> +    "add": "^2.0.6",
done

2023-01-17 22:40 UTC, keliumJU commented on okdoseweb/package.json
> +    "yarn": "^1.22.19"
this comes from the main branch, just moved it but done

2023-01-17 22:42 UTC, keliumJU commented on okdoseweb/package.json
>      "eslint-config-airbnb": "^19.0.4",
not only `add`, `babel-plugin-module-resolver` that was the plugin that @einerzg  recommended.

2023-01-17 22:42 UTC, keliumJU commented on okdoseweb/index.js
>  // React
Done, and also removed other unnecessary dependencies

2023-01-18 16:26 UTC, jcamilocp approved these changes
LGTM!

2023-01-18 16:47 UTC, merged