Create smart contract for Miltefosine prescription
kommitters/okdose-dapp pull request #39
Opened 2023-01-19 20:42 UTC by keliumJU

## Description

The translation keys were added for the Miltefosine contract. Also, updated the dependencies in the packages.json of okdose and okdoseweb because the yarn install automatically adds plugins that the parcel blunder needs.

Solves #29 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

2023-01-19 21:02 UTC, jcamilocp requested changes

2023-01-19 21:02 UTC, jcamilocp commented on okdoseweb/assets/locales/en/translation.json
> +    },
These keys are not in the scope of this ticket, but as long as we don't have the design yet, should we add them here? @LauraVilladakommit

2023-01-19 21:16 UTC, LauraVilladakommit commented on okdoseweb/assets/locales/en/translation.json
> +    },
@jcamilocp, as the contracts response is the keys, we need to add the translation when doing the formulation file.

2023-01-20 13:56 UTC, jcamilocp approved these changes

2023-01-20 16:21 UTC, jcamilocp approved these changes

2023-01-23 14:34 UTC, merged