Set up for integration tests for smart contracts
kommitters/okdose-dapp pull request #51
Opened 2023-01-26 00:09 UTC by LauraVilladakommit

## Description

We add the integration test set-up to create all the integration tests missing for Leishmaniasis

Fixes #35 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-01-27 15:56 UTC, jcamilocp requested changes

2023-01-27 15:56 UTC, jcamilocp commented on integration-tests/envVariables.json.example
> +  "MAIN_ACCOUNT": "ok-medicines.testnet",
Question: can't we use the same `contracts.env` file for this?

2023-01-27 15:56 UTC, jcamilocp commented on integration-tests/src/miltefosine.ava.ts
> +test.beforeEach(async (t) => {
I see a lot of code duplicated. Can we refactor the code to prevent that?

2023-01-27 16:24 UTC, miguelnietoa commented on integration-tests/package.json
> +  "license": "(MIT AND Apache-2.0)",
Why is the license "(MIT AND Apache-2.0)"?

2023-01-27 17:06 UTC, LauraVilladakommit commented on integration-tests/envVariables.json.example
> +  "MAIN_ACCOUNT": "ok-medicines.testnet",
@jcamilocp, No, we can't. We tried to do it in several ways but ava does not recognize .env files to do the configuration set-up in `ava.config.js`. The only way to use env variables in the test environment is like this.

2023-01-27 17:11 UTC, LauraVilladakommit commented on integration-tests/src/miltefosine.ava.ts
> +test.beforeEach(async (t) => {
@jcamilocp We tried also to define the contract just with a constant when importing to not use so many assignments but ava works with that t variable as an argument define in the ava context, this means it is not possible to pass the contract const like the test argument.

2023-01-27 19:39 UTC, LauraVilladakommit commented on integration-tests/package.json
> +  "license": "(MIT AND Apache-2.0)",
I changed it to Apache-2.0

2023-01-30 13:39 UTC, jcamilocp commented on integration-tests/src/miltefosine.ava.ts
> +test.beforeEach(async (t) => {
But we can define the function inside the before and after blocks in another file and then use them here, am I wrong?

2023-01-30 13:39 UTC, jcamilocp commented on integration-tests/src/miltefosine.ava.ts
> +    console.log('Failed to tear down the worker:', error);
Let's solve those warnings

2023-01-30 13:39 UTC, jcamilocp commented on package.json
>      "lint:fix": "cd okdose && yarn eslint --fix . && cd .. && cd okdoseweb && yarn eslint --fix .",
Should we modify this too?

2023-01-30 13:47 UTC, jcamilocp commented on .env.example
> +NMETIL_CONTRACT="prescription.ok-medicines.testnet"
I think we should keep the .env.example with fake values, even if we're providing these values to all contributors

2023-01-30 16:57 UTC, LauraVilladakommit commented on package.json
>      "lint:fix": "cd okdose && yarn eslint --fix . && cd .. && cd okdoseweb && yarn eslint --fix .",
If we want to run the integration tests in the CI, we will need to define the scripts here in the project root.

2023-01-30 16:59 UTC, LauraVilladakommit commented on .env.example
> +NMETIL_CONTRACT="prescription.ok-medicines.testnet"
@jcamilocp So are we going to write this info in the README to ask the contributors to write it in the .env file?

2023-01-30 17:05 UTC, jcamilocp commented on .env.example
> +NMETIL_CONTRACT="prescription.ok-medicines.testnet"
Yes, I think it'll be the best

2023-01-30 17:06 UTC, jcamilocp commented on package.json
>      "lint:fix": "cd okdose && yarn eslint --fix . && cd .. && cd okdoseweb && yarn eslint --fix .",
We can review how to run the integration test from the CI. I think it's very important to add it to the flow

2023-01-30 19:24 UTC, jcamilocp commented on integration-tests/package.json
> +  "version": "1.0.0",
Is this version correct?

2023-01-30 19:24 UTC, jcamilocp commented on integration-tests/package.json
> +  "version": "1.0.0",
I think we're using 0.1.0 for this release.

2023-01-31 14:22 UTC, jcamilocp approved these changes
LGTM! Let's plan the CI for a new task

2023-01-31 14:23 UTC, merged