Setting up Frontend Basic Functionality
kommitters/okdose-dapp pull request #65
Opened 2023-02-07 16:20 UTC by keliumJU

## Description

Add Basic Router
Create the Home Container
Add Card for Information displaying

![image](https://user-images.githubusercontent.com/48634254/217302023-115de50f-fcc6-4042-b889-bc8acc1198a6.png)

Resolves #4

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-02-09 15:37 UTC, keliumJU commented on okdose-web/App.js
> +function App() {
I like it, it looks more readable, unfortunately I wasn't using **prettier** or **eslint** to format the code, so now everything is automated with the `yarn format` command from the root of the project.

2023-02-09 15:40 UTC, keliumJU commented on okdose-web/components/Prescription.js
> +import * as React from 'react'
it's true, it seems unnecessary, now it is only imported from **App.js** the following way: 
`import React from 'react';`

2023-02-09 15:50 UTC, keliumJU commented on okdose-web/components/Prescription.js
> +      <p>{ prescription.volumeDose }</p>
Yes, it seems cleaner to me, let's follow that approach.

2023-02-09 16:49 UTC, keliumJU commented on okdose-web/components/common/ButtonBack.js
> +function ButtonBack() {
I think so, but I'm going to take you at your word in the comments below and make a single "**HomeButton**" for _back, calculate and update._

2023-02-09 22:03 UTC, keliumJU commented on okdose-web/components/common/ButtonBack.js
> +    <svg viewBox="0 0 10 18" fill="none" xmlns="http://www.w3.org/2000/svg" className="w-4 h-4">
would be ideal, the problem is that it uses the blunder parcel and currently has some [**busgs with svg**](https://github.com/parcel-bundler/parcel/issues/7587) rendering as component.
so I think we use this other approach based on the parcel documentation to use [**svg in JavaScript**](https://parceljs.org/languages/svg/#svg-in-javascript) via the <img> tag 

it would look something like this at the end

```
import Back from '../../assets/images/icons/back.svg';
...
<img src={Back} alt='icon-back' />
```

2023-02-09 22:07 UTC, keliumJU commented on okdose-web/components/common/ButtonWeight.js
> +export default ButtonWeight
this was a very good idea, we created a single component for those buttons given their similarity, for this we relied on the concept of [**dynamic classes**](https://tailwindcss.com/docs/content-configuration#dynamic-class-names) of Tailwind.

now we only have the button component

```
<Button type='weight' titleKey='app_info.weight_button'/>
<Button type='back' titleKey='app_info.back_button'/>
```

2023-02-09 22:17 UTC, keliumJU commented on okdose-web/components/common/CardWeight.js
> +      <TitleCardWeight title={'Results'}/>
of course, that works `<TitleCardWeight title='Results'/>,` and the space at the end of the component call, is also automated with `yarn format`

2023-02-09 22:18 UTC, keliumJU commented on okdose-web/components/common/CardWeight.js
> +export default CardWeight
I like it :)

2023-02-09 22:20 UTC, keliumJU commented on okdose-web/containers/Home.js
> +        <CardInformationDisplay />
not necessarily, it was to check the separation when it is as if it were a list.

2023-02-09 22:21 UTC, keliumJU commented on okdose-web/containers/Home.js
> +        await wallet.startUp();
we definitely needed the format, and this is also done by `yarn format` :)

2023-02-09 22:27 UTC, keliumJU commented on okdose-web/components/common/TitleCardWeight.js
> +function TitleCardWeight({title}) {
reference that it is the title of the card with which we modify the weight of a person.

![image](https://user-images.githubusercontent.com/48634254/217953185-248365a7-e783-4823-b06c-3c6d1810bb0f.png)

it has the shape of a button but it is not a button, it is the dynamic title of what the weight card displays

2023-02-09 22:28 UTC, keliumJU commented on okdose-web/components/Prescription.js
> +      <h1 className="text-3xl underline text-customColor">{ t(`${prescription.name}`) }</h1>
now automatic with `yarn format`

2023-02-09 22:35 UTC, keliumJU commented on okdose-web/components/common/TitleCardWeight.js
> +function TitleCardWeight({title}) {
Now I changed the `button` label to `div` inside the component, thanks for the distinction :)

2023-02-09 22:42 UTC, keliumJU commented
@JoseCastroA , @LauraVilladakommit , @jcamilocp This PR will be **huge** only for this occasion, because we were **not using** the **format** defined in **prettier** and also with the **comments** of @JoseCastroA  we will adjust the space after the name of the parent function with eslint(this can change) `"space-before-function-paren": ["error", "always"]`, all this will be done automatically with the command `yarn format` executed from the root of the project.

2023-02-09 23:47 UTC, keliumJU commented on okdose-web/App.js
> +function App() {
mm can you share me some example, I don't understand very well what you mean, before it was as **airbnb** extension it was changed by `eslint:recommended` in **.eslintrc.json**

2023-02-10 16:49 UTC, JoseCastroA commented on okdose-web/App.js
> +function App() {
Hi @keliumJU, this is the package https://www.npmjs.com/package/eslint-config-airbnb

You can find a lot of guides about how to include it in a project or your local environment

2023-02-10 16:51 UTC, JoseCastroA commented on okdose-web/components/common/ButtonBack.js
> +    <svg viewBox="0 0 10 18" fill="none" xmlns="http://www.w3.org/2000/svg" className="w-4 h-4">
That's ok @keliumJU

2023-02-10 17:09 UTC, JoseCastroA requested changes
@keliumJU Good job, just a few final comments 

cc/ @LauraVilladakommit @jcamilocp

2023-02-10 17:09 UTC, JoseCastroA commented on okdose-web/components/common/Button.js
> +Button.propTypes = {
@keliumJU Just to be annoying, could you add a space here? Just to separate propsTypes functions 

```
};

Button.propTypes = {
```

2023-02-10 17:09 UTC, JoseCastroA commented on okdose-web/components/common/DisplayCardInformation.js
> +import Next from '../../assets/images/icons/next.svg';
@keliumJU Variable names should start with lower case, also, we can named it better, like nextIcon

What do you think? This applies for all SVG imports

2023-02-10 17:09 UTC, JoseCastroA commented on okdose-web/components/common/TitleWeightCard.js
> +import PropTypes from 'prop-types';
Can you add a space here? @keliumJU After all imports, we should have a space

```
import PropTypes from 'prop-types';

function TitleWeightCard ({title}) {
```

2023-02-10 20:00 UTC, keliumJU commented on okdose-web/components/common/TitleWeightCard.js
> +import PropTypes from 'prop-types';
ok, I will add this rule: `"import/newline-after-import": ["error", {"count": 1}]`

2023-02-10 20:44 UTC, keliumJU commented on okdose-web/components/common/Button.js
> +Button.propTypes = {
I did not find a way to automate that line break maybe with `padding-line-between-statements`, but it does not have support for this pattern `};` however I will keep this comment in mind.

2023-02-10 21:05 UTC, keliumJU commented on okdose-web/components/common/DisplayCardInformation.js
> +import Next from '../../assets/images/icons/next.svg';
yes I like the idea, because we don't use the icon as a component we just render it in an element, I will also use a more descriptive name like **forwardArrowIcon**

2023-02-10 21:20 UTC, keliumJU commented on okdose-web/App.js
> +function App() {
Thank you very much, I will check that out

2023-02-13 17:23 UTC, einerzg requested changes
@keliumJU, please check the comments!!!

2023-02-13 17:23 UTC, einerzg commented on okdose-web/components/common/Button.js
> +  titleKey: PropTypes.string
Shouldn't both be required?

2023-02-13 17:23 UTC, einerzg commented on okdose-web/components/common/DisplayCardInformation.js
> +  );
why doesn't this use i18n?

2023-02-13 17:23 UTC, einerzg commented on okdose-web/components/common/TitleWeightCard.js
> +function TitleWeightCard ({title}) {
why this is a component?

2023-02-13 17:23 UTC, einerzg commented on okdose-web/components/common/Button.js
> +  titleKey: 'app_info.weight_button'
why send the key and not the value? it is good practice to have dumb components

2023-02-13 17:23 UTC, einerzg commented on okdose-web/components/common/WeightCard.js
> +      <TitleWeightCard title='Dosage' />
why not use i18n? for `Dosage`

2023-02-13 17:23 UTC, einerzg commented on okdose-web/containers/Home.js
> +    getPrescription().catch(console.error);
`console.error`. what do you use to manage the logs in the application?

2023-02-13 17:23 UTC, einerzg commented on okdose-web/containers/Home.js
> +      const response = await prescribeMiltefosine(nearInterface, 70);
70?

2023-02-13 17:23 UTC, einerzg commented on okdose-web/i18n/i18n.js
> +    translation: translationFR
how do we manage the translation information for fr? Do we have the information?

2023-02-13 17:23 UTC, einerzg commented on okdose-web/router/routeConfig.js
> +            <Link to='/home'>Home</Link>
i18n?

2023-02-14 13:47 UTC, keliumJU commented on okdose-web/components/common/DisplayCardInformation.js
> +  );
here must be part of the information of a contract, the corresponding with the name and the presentation and if it must be translated.

2023-02-14 13:48 UTC, keliumJU commented on okdose-web/components/common/TitleWeightCard.js
> +function TitleWeightCard ({title}) {
because it has a dynamic title and the className is long

2023-02-14 13:54 UTC, keliumJU commented on okdose-web/components/common/WeightCard.js
> +      <TitleWeightCard title='Dosage' />
is part of the translation of the info, it's just being formed

2023-02-14 14:15 UTC, keliumJU commented on okdose-web/components/common/Button.js
> +  titleKey: 'app_info.weight_button'
it is a very good idea, but I think we should think about how to structure the big objects of the contracts, like: miltefosine, n-methyl ..., which have a lot of keys, we will write it down for another issue.

2023-02-14 14:27 UTC, keliumJU commented on okdose-web/components/PrescriptionView.js
> +function PrescriptionView ({prescription}) {
I thought it was not possible, but in the end it looks like this:
`function PrescriptionView ({prescription:{name, presentation, treatmentTime, warning, note, weightDose, volumeDose}}) {`

2023-02-14 14:28 UTC, keliumJU commented on okdose-web/components/common/Button.js
> +  titleKey: PropTypes.string
has default values, the require will give a warning if it is not written.

2023-02-14 14:30 UTC, keliumJU commented on okdose-web/components/PrescriptionView.js
> +  title: PropTypes.object
I change it by prescription, I missed it.

2023-02-14 14:44 UTC, keliumJU commented on okdose-web/i18n/i18n.js
> +    translation: translationFR
the French translation is not complete, but it has made significant progress, I suppose it can be maintained until it is finally completed.

2023-02-14 14:45 UTC, keliumJU commented on okdose-web/router/routeConfig.js
> +            <Link to='/home'>Home</Link>
this was just an example in reality you will not access home like this

2023-02-14 14:49 UTC, keliumJU commented on okdose-web/containers/Home.js
> +    getPrescription().catch(console.error);
this issue has not been taken into account yet, we will deal with it in a future issue, we may have to create our own logger handler: https://meticulous.ai/blog/getting-started-with-react-logging/, or use a library.

2023-02-14 14:55 UTC, keliumJU commented on okdose-web/containers/Home.js
> +      const response = await prescribeMiltefosine(nearInterface, 70);
Corrected

2023-02-14 15:03 UTC, einerzg commented on okdose-web/components/common/TitleWeightCard.js
> +function TitleWeightCard ({title}) {
Will you reuse this card in other components?

2023-02-14 15:05 UTC, einerzg commented on okdose-web/containers/Home.js
> +    getPrescription().catch(console.error);
it is necessary!!

2023-02-14 15:49 UTC, keliumJU commented on okdose-web/components/common/TitleWeightCard.js
> +function TitleWeightCard ({title}) {
it is true, it is not reused, I am going to change it to a `span` tag and pass it to the WeightCard component, only used there

2023-02-14 19:28 UTC, einerzg requested changes

2023-02-14 19:28 UTC, einerzg commented on okdose-web/containers/Home.js
> +  const weight = 70;
`const DEFAULT_WEIGHT =  70;`

2023-02-14 19:28 UTC, einerzg commented on okdose-web/i18n/i18n.js
> +    translation: translationFR
If this doesn't cause any kind of issue, that's fine.

2023-02-14 19:28 UTC, einerzg commented on okdose-web/components/common/Button.js
> +  titleKey: 'app_info.weight_button'
I don't see why not apply the change now

2023-02-15 20:12 UTC, JoseCastroA approved these changes

2023-02-15 20:14 UTC, merged