Add the Welcome component
kommitters/okdose-dapp pull request #76
Opened 2023-02-15 21:56 UTC by keliumJU

## Description

Add the welcome page, according to the design 

![image](https://user-images.githubusercontent.com/48634254/219177921-3801c51a-2dbb-48a0-87ff-48c6b3196a04.png)

Resolves #63

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-02-15 22:47 UTC, LauraVilladakommit requested changes

2023-02-15 22:47 UTC, LauraVilladakommit commented on okdose-web/assets/locales/es/translation.json
> +    "footer_credits": "Creditos"
It should be "Créditos" with an accent

2023-02-15 22:47 UTC, LauraVilladakommit commented on okdose-web/components/Welcome.js
> +    >
Fix the indentation

2023-02-15 22:47 UTC, LauraVilladakommit commented on okdose-web/components/Welcome.js
> +      '
Fix the indentation and move the quote to line 25

2023-02-15 22:47 UTC, LauraVilladakommit commented on okdose-web/components/common/Footer.js
> +      )}
Here, to avoid an empty else `<></>` you could use `&&` instead the ternary operator `? true : false`

2023-02-15 22:47 UTC, LauraVilladakommit commented on okdose-web/tailwind.config.js
> +          'url(\'/assets/images/background-mobile.png\')'
I think it is better to say "welcome-background" and "welcome-background-mobile"

2023-02-16 13:18 UTC, keliumJU commented on okdose-web/components/Welcome.js
> +    >
I think one option would be in one line and then use **word wrap** in the editor if it is Visual Studio code would be to use `Alt + z` commands

2023-02-16 14:13 UTC, LauraVilladakommit approved these changes

2023-02-16 14:55 UTC, jcamilocp reviewed
Hi @keliumJU, I just left some comments

2023-02-16 14:55 UTC, jcamilocp commented on okdose-web/App.js
> +import i18n from './i18n/i18n';
Can we switch the name? This import here looks odd

2023-02-16 14:55 UTC, jcamilocp commented on okdose-web/components/common/Footer.js
> +  showExtraInfo: PropTypes.string
Is this a string? Because I'm seeing we're using it as a boolean

2023-02-16 14:55 UTC, jcamilocp commented on okdose-web/components/common/FooterButton.js
> +      <button className='flex flex-col items-center justify-center mt-5 bg-blue-pale text-gray-700 not-italic font-semibold text-sm p-3 w-full'>
I'd change this line too. Looks so long.

2023-02-16 15:02 UTC, keliumJU commented on okdose-web/App.js
> +import i18n from './i18n/i18n';
by changing i18n.js to index.js, it would be called like this: 
`import i18n from './i18n';`

2023-02-16 19:04 UTC, jcamilocp reviewed
![image](https://user-images.githubusercontent.com/51332818/219462693-2b598028-6136-4f90-a7a7-fc8cf6f19673.png)

 This shouldn't be here, right?

2023-02-16 19:34 UTC, jcamilocp approved these changes
LGTM

2023-02-16 19:36 UTC, merged