Create the dropdown menu
kommitters/okdose-dapp pull request #77
Opened 2023-02-16 20:48 UTC by keliumJU

## Description

Add dropdown menu according to the design
![image](https://user-images.githubusercontent.com/48634254/219483386-b53f0759-05ea-4ff3-abb3-6af0b733b636.png)

Resolves #61

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-02-16 21:00 UTC, jcamilocp requested changes
Hil, I added some comments. Also, remove the wrong reference to the private module, please.

Thanks!

2023-02-16 21:00 UTC, LauraVilladakommit requested changes

2023-02-16 21:00 UTC, LauraVilladakommit commented on okdose-web/tests/DropdownMenu.test.js
> +});
We should text the translations, not only if it is defined.

2023-02-16 22:51 UTC, keliumJU commented on okdose-web/assets/styles/main.css
> +  padding: 6px;
I'm going to change it to tailwind utility classes, with dynamic measures

2023-02-17 16:19 UTC, keliumJU commented on okdose-web/tests/DropdownMenu.test.js
> +});
first we define that the translation key exists, then we check the burned text in the language we are testing.

```
    expect(
      screen.getByText(
        i18n.getDataByLanguage('en').translation.leishmaniasis.name
      )
    ).toBeDefined();
```

2023-02-17 16:19 UTC, keliumJU commented on okdose-web/components/common/Section.js
> +      <div className='header bg-white text-neutral-700' {...getToggleProps()}>
you are right, change made

2023-02-17 16:21 UTC, keliumJU commented on okdose-web/assets/styles/main.css
> +}
I made the change to `p-2` with the tailwind utility classes and the `cursor-pointer` is default.

2023-02-17 16:22 UTC, keliumJU commented on okdose-web/components/common/Section.js
> +  const config = {
we only need it for the dropdown, I think it's fine just there

2023-02-17 16:26 UTC, keliumJU commented on okdose-web/components/common/Section.js
> +/* eslint-disable react/jsx-props-no-spreading */
the dropdown needs this configuration, as it is part of the **react-collapse** library
` <div className='header bg-white text-neutral-700' {...getToggleProps()}>`
and the spred operator is part of modern javascript

2023-02-17 16:27 UTC, keliumJU commented on okdose-web/components/DropdownMenu.js
> +      <Section
this was refactored with the object of okdose/index.js

2023-02-17 17:19 UTC, jcamilocp reviewed
Code looks a lot cleaner! Added some comments

2023-02-17 17:19 UTC, jcamilocp commented on okdose/app/index.js
> +import byVectorsIcon from '../../okdose-web/assets/images/icons/byVectorsIcon.svg';
Is this import absolutely necessary? Can't we export only text referencing the images here?

2023-02-17 17:19 UTC, jcamilocp commented on okdose-web/.eslintrc.json
> +    "react/jsx-props-no-spreading": ["off"],
Why turn off this rule?

2023-02-17 17:19 UTC, jcamilocp commented on okdose-web/containers/Home.js
> +          <h1 className='uppercase overflow-hidden text-lg'>Mycobactéries</h1>
Is this text correct?

2023-02-17 19:23 UTC, keliumJU commented on okdose/app/index.js
> +import byVectorsIcon from '../../okdose-web/assets/images/icons/byVectorsIcon.svg';
The closest thing to change the import according to the parcel documentation would be this: 

const transmissionTypes = {
  byVectors: {
    name: transmittedByVectors.name,
    icon: new URL('../../okdose-web/assets/images/icons/byVectorsIcon.svg', import.meta.url),

2023-02-17 19:27 UTC, keliumJU commented on okdose-web/containers/Home.js
> +          <h1 className='uppercase overflow-hidden text-lg'>Mycobactéries</h1>
my error, it stayed when with the tests of the capital letters, I already remove it.

2023-02-17 21:57 UTC, jcamilocp commented on okdose/app/index.js
> +    types: {
What are these `types` for? I think we should not access that deep here

2023-02-17 22:12 UTC, keliumJU commented on okdose/app/index.js
> +    types: {
`types` refers to the types of diseases, and inside it refers to the parent objects of each disease: leishmaniasis, chagas and malaria.

2023-02-17 22:44 UTC, jcamilocp approved these changes
LGTM!

2023-02-17 22:48 UTC, LauraVilladakommit approved these changes

2023-02-17 22:48 UTC, merged