Create card component
kommitters/okdose-dapp pull request #85
Opened 2023-02-23 21:12 UTC by keliumJU

## Description

Create card component
![image](https://user-images.githubusercontent.com/48634254/221031285-85a4ce18-9e08-42ac-9745-07d6037ad7b1.png)

Resolves #10

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-02-23 21:46 UTC, jcamilocp requested changes

2023-02-23 21:46 UTC, jcamilocp commented on okdose-web/assets/locales/es/translation.json
> +      "preparation": "Preparacion"
Preparación

2023-02-23 21:46 UTC, jcamilocp commented on okdose-web/containers/Home.js
> +  const wallet = new Wallet({createAccessKeyFor: process.env.MAIN_ACCOUNT});
Let's remove every sign we're calling a smart contract. Let's show some cards with placeholders instead of loading real data. Calling smart contracts is not in the scope of this issue

2023-02-23 21:58 UTC, LauraVilladakommit requested changes

2023-02-23 21:58 UTC, LauraVilladakommit commented on okdose-web/assets/locales/en/translation.json
>    },
I think we could move the group key `card_info` out of the `app_info` because `app_info` only contains the general information for the welcome and home pages.

2023-02-23 21:58 UTC, LauraVilladakommit commented on okdose-web/assets/locales/es/translation.json
>    },
Same here, we should move the `card_info`out of `app_info` key group

2023-02-23 21:58 UTC, LauraVilladakommit commented on okdose-web/components/common/DisplayCardInformation.js
> +  type
As the icons are not only for dosage but general (for treatment time, warning, etc.), we should change the name `showDoseIcon` to `showIcon` and `cardDoseIcon` to `cardIcon`. This way you do not think that the icon is only for the dosing section.

2023-02-23 21:58 UTC, LauraVilladakommit commented on okdose-web/components/common/DisplayCardInformation.js
> +        <div className='py-5 text-sm font-normal'>
Do we need the class `font-normal`? I think the default font weight is already 400.

2023-02-23 21:58 UTC, LauraVilladakommit commented on okdose-web/components/common/DisplayCardInformation.js
> +        <div className='flex flex-row justify-end items-center text-sm not-itali font-normal mb-5'>
`no_itali` has a typo and anyway the default value is not italic, so we can delete it. I think is the same for the `font-normal` class.

2023-02-23 21:58 UTC, LauraVilladakommit commented on okdose-web/containers/Home.js
> +  const wallet = new Wallet({createAccessKeyFor: process.env.MAIN_ACCOUNT});
We should move this line after the hooks.

2023-02-23 21:58 UTC, LauraVilladakommit commented on okdose-web/tests/DisplayCardInformation.test.js
> +describe('It renders of DisplayCardInformation component', () => {
You can delete the preposition `of`

2023-02-23 21:58 UTC, LauraVilladakommit commented on okdose-web/tests/DisplayCardInformation.test.js
> +  test('DisplayCardInformation component renders with translations in English', () => {
It is better to say `DisplayCardInformation component renders with English translations when type is warning`

2023-02-23 21:58 UTC, LauraVilladakommit commented on okdose-web/tests/DisplayCardInformation.test.js
> +  test('DisplayCardInformation component renders with translations in Spanish', () => {
Same here: `DisplayCardInformation component renders with Spanish translations when type is warning`

2023-02-23 21:58 UTC, LauraVilladakommit commented on okdose-web/tests/DisplayCardInformation.test.js
> +  test('DisplayCardInformation component renders with translations in English when type is info', () => {
Here you can change to `DisplayCardInformation component renders with English translations when type is info`

2023-02-23 21:58 UTC, LauraVilladakommit commented on okdose-web/tests/DisplayCardInformation.test.js
> +});
It misses the test for Spanish translation when the type is info

2023-02-23 22:30 UTC, keliumJU commented on okdose-web/components/common/DisplayCardInformation.js
> +  type
I put dose because that is the title of the CardinputCardWeight when the dosage for a prescription is displayed, But I like your proposal even more.
![image](https://user-images.githubusercontent.com/48634254/221045207-d8f23e24-9ca9-4de7-8adc-e96670b95313.png)

2023-02-23 22:32 UTC, keliumJU commented on okdose-web/containers/Home.js
> +  const wallet = new Wallet({createAccessKeyFor: process.env.MAIN_ACCOUNT});
we will not use the contract data, it will disappear.

2023-02-23 22:33 UTC, keliumJU commented on okdose-web/components/common/DisplayCardInformation.js
> +        <div className='flex flex-row justify-end items-center text-sm not-itali font-normal mb-5'>
removed

2023-02-23 22:39 UTC, keliumJU commented on okdose-web/tests/DisplayCardInformation.test.js
> +});
it is true thank you

2023-02-23 22:54 UTC, LauraVilladakommit approved these changes

2023-02-23 23:03 UTC, jcamilocp requested changes

2023-02-23 23:03 UTC, jcamilocp commented on okdose-web/containers/Home.js
> +                type='warning'
I think we should standardize these types, maybe declaring them as constants

2023-02-23 23:38 UTC, keliumJU commented on okdose-web/containers/Home.js
> +                type='warning'
I created a **constants** folder to call them from there, this could be an option.

2023-02-24 15:45 UTC, LauraVilladakommit requested changes

2023-02-24 15:45 UTC, LauraVilladakommit commented on okdose-web/constants/index.js
> +};
It misses a new line here

2023-02-24 15:45 UTC, LauraVilladakommit commented on okdose-web/containers/Home.js
>            <p className='mb-2 p-5 text-dark-gray text-center'>
We should create a custom class in the Tailwind config file for the size 870px

2023-02-24 15:45 UTC, LauraVilladakommit commented on okdose-web/containers/Home.js
> +          <div className='hidden min-[870px]:block md:px-10 md:pt-16 md:pb-5 lg:pt-28'>
Here we use the size again, so it is better to create the custom class and the code will be easier to maintain

2023-02-24 15:57 UTC, keliumJU commented on okdose-web/containers/Home.js
>            <p className='mb-2 p-5 text-dark-gray text-center'>
Sounds good to me, I'm going to set up a 2md screen for that size.

![image](https://user-images.githubusercontent.com/48634254/221225419-f8ef5df1-0e6b-4f9a-8f58-7bb2f5227e58.png)

2023-02-24 16:08 UTC, LauraVilladakommit approved these changes

2023-02-24 17:00 UTC, jcamilocp approved these changes

2023-02-24 17:00 UTC, merged